export const PROFESSIONS_ES = [
    'Abogado/a',
    'Administrador/a de Empresas',
    'Agente de Seguros',
    'Agente de Viajes',
    'Agrónomo/a',
    'Analista Financiero/a',
    'Analista de Sistemas',
    'Arquitecto/a',
    'Asistente Administrativo/a',
    'Asistente Contable',
    'Asistente Ejecutivo/a',
    'Auditor/a',
    'Bacteriólogo/a',
    'Biólogo/a',
    'Bombero/a',
    'Cajero/a',
    'Carpintero/a',
    'Chef / Cocinero/a',
    'Chofer / Conductor/a',
    'Ciencias de la Comunicación',
    'Comerciante',
    'Contador/a Público/a',
    'Coordinador/a Comercial',
    'Coordinador/a de Logística',
    'Coordinador/a de RRHH',
    'Cosmétologa / Esteticista',
    'Costurero/a / Modista',
    'Decorador/a de Interiores',
    'Dentista / Odontólogo/a',
    'Diseñador/a Gráfico/a',
    'Diseñador/a Industrial',
    'Diseñador/a de Modas',
    'Diseñador/a Web',
    'Economista',
    'Educador/a Especial',
    'Electricista',
    'Enfermero/a',
    'Estadístico/a',
    'Farmacéutico/a',
    'Filósofo/a',
    'Físico/a',
    'Fisioterapeuta',
    'Fotógrafo/a',
    'Geógrafo/a',
    'Geólogo/a',
    'Gerente Comercial',
    'Gerente de Ventas',
    'Historiador/a',
    'Ingeniero/a Agrónomo/a',
    'Ingeniero/a Ambiental',
    'Ingeniero/a Civil',
    'Ingeniero/a de Alimentos',
    'Ingeniero/a de Minas',
    'Ingeniero/a de Sistemas',
    'Ingeniero/a Eléctrico/a',
    'Ingeniero/a Industrial',
    'Ingeniero/a Mecánico/a',
    'Ingeniero/a Petroquímico/a',
    'Ingeniero/a Químico/a',
    'Instructor/a / Facilitador/a',
    'Intérprete / Traductor/a',
    'Jefe de Almacén',
    'Jefe de Operaciones',
    'Jefe de Ventas',
    'Kinesiólogo/a',
    'Licenciado/a en Administración',
    'Licenciado/a en Comunicación',
    'Licenciado/a en Contabilidad',
    'Licenciado/a en Educación',
    'Licenciado/a en Enfermería',
    'Licenciado/a en Informática',
    'Licenciado/a en Psicología',
    'Licenciado/a en Trabajo Social',
    'Logístico/a',
    'Maestro/a / Docente',
    'Médico/a General',
    'Médico/a Especialista',
    'Mercadólogo/a',
    'Meteorólogo/a',
    'Microbiólogo/a',
    'Músico/a',
    'Nutricionista / Dietista',
    'Operador/a de Equipos',
    'Optómetra',
    'Panadero/a / Repostero/a',
    'Periodista',
    'Plomero/a',
    'Productor/a Audiovisual',
    'Programador/a',
    'Promotor/a de Ventas',
    'Psicólogo/a',
    'Publicista',
    'Químico/a',
    'Radiólogo/a',
    'Recepcionista',
    'Representante Comercial',
    'Secretario/a',
    'Sociólogo/a',
    'Supervisor/a de Ventas',
    'Técnico/a Automotriz',
    'Técnico/a de Refrigeración',
    'Técnico/a Electrónico/a',
    'Técnico/a en Sistemas',
    'Técnico/a Radiologista',
    'Tecnólogo/a Médico/a',
    'Terapeuta',
    'Topógrafo/a',
    'Trabajador/a Social',
    'TSU en Administración',
    'TSU en Informática',
    'TSU en Mercadeo',
    'TSU en Recursos Humanos',
    'Vendedor/a',
    'Veterinario/a',
    'Zootecnista',
];
